<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121203163256 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		// $this->addSql("ALTER TABLE typo3_singlesignon_server_domain_model_accesstoken DROP FOREIGN KEY FK_BC326C58680E437");
		$this->addSql("ALTER TABLE typo3_singlesignon_server_domain_model_ssoclient DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE typo3_singlesignon_server_domain_model_ssoclient CHANGE identifier baseuri VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE typo3_singlesignon_server_domain_model_ssoclient ADD PRIMARY KEY (baseuri)");
		$this->addSql("ALTER TABLE typo3_singlesignon_server_domain_model_accesstoken ADD CONSTRAINT FK_BC326C58680E437 FOREIGN KEY (ssoclient) REFERENCES typo3_singlesignon_server_domain_model_ssoclient (baseuri)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE typo3_singlesignon_server_domain_model_accesstoken DROP FOREIGN KEY FK_BC326C58680E437");
		$this->addSql("ALTER TABLE typo3_singlesignon_server_domain_model_accesstoken ADD CONSTRAINT FK_BC326C58680E437 FOREIGN KEY (ssoclient) REFERENCES typo3_singlesignon_server_domain_model_ssoclient (identifier)");
		$this->addSql("ALTER TABLE typo3_singlesignon_server_domain_model_ssoclient DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE typo3_singlesignon_server_domain_model_ssoclient CHANGE baseuri identifier VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE typo3_singlesignon_server_domain_model_ssoclient ADD PRIMARY KEY (identifier)");
	}
}

?>