<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121213131409 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("DROP TABLE typo3_singlesignon_server_domain_model_accesstoken");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE typo3_singlesignon_server_domain_model_accesstoken (identifier VARCHAR(255) NOT NULL, ssoclient VARCHAR(255) DEFAULT NULL, account VARCHAR(40) DEFAULT NULL, expirytime INT NOT NULL, sessionid VARCHAR(255) NOT NULL, INDEX IDX_BC326C58680E437 (ssoclient), INDEX IDX_BC326C587D3656A4 (account), PRIMARY KEY(identifier)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE typo3_singlesignon_server_domain_model_accesstoken ADD CONSTRAINT FK_BC326C58680E437 FOREIGN KEY (ssoclient) REFERENCES typo3_singlesignon_server_domain_model_ssoclient (servicebaseuri) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE typo3_singlesignon_server_domain_model_accesstoken ADD CONSTRAINT FK_BC326C587D3656A4 FOREIGN KEY (account) REFERENCES typo3_flow_security_account (persistence_object_identifier) ON DELETE CASCADE");
	}
}

?>