TYPO3:
  SingleSignOn:
    Server:
      server:
        keyPairUuid: 'bb5abb57faa122cc031e3c904db3d751'
    Client:
      client:
        serviceBaseUri: 'http://ssoclient/sso'
        keyPairUuid: 'bb45dfda9f461c22cfdd6bbb0a252d8e'
      server:
        TestServer:
          publicKeyUuid: 'bb5abb57faa122cc031e3c904db3d751'
          serviceBaseUri: 'http://ssoserver/test/sso'

  Flow:
    security:
      cryptography:
        RSAWalletServicePHP:
          keystorePath: %FLOW_PATH_DATA%Temporary/Testing/RsaWalletData
      authentication:
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: WebRedirect
            entryPointOptions:
              uri: 'login'
