TYPO3:
  SingleSignOn:
    Server:
      # From fixtures
      ssoServerKeyPairUuid: 'bb5abb57faa122cc031e3c904db3d751'
    Client:
      ssoClientIdentifier: 'client-01'
      ssoServerEndpointUri: 'http://ssoserver/test/sso/authentication'
      ssoClientKeyPairUuid: 'bb45dfda9f461c22cfdd6bbb0a252d8e'
      ssoServerPublicKeyUuid: 'bb5abb57faa122cc031e3c904db3d751'
  Flow:
    security:
      cryptography:
        RSAWalletServicePHP:
          keystorePath: %FLOW_PATH_DATA%Temporary/Testing/RsaWalletData
      authentication:
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: WebRedirect
            entryPointOptions:
              uri: 'login'
