-
  name: 'SSO authentication endpoint with action'
  uriPattern: 'authentication(/{@action})'
  defaults:
    '@package':    'TYPO3.SingleSignOn.Server'
    '@controller': 'Authentication'
    '@action':     'authenticate'
    '@format':     'html'
  appendExceedingArguments: TRUE

-
  name: 'SSO access token redemption'
  uriPattern: 'redeem/{accessToken}'
  defaults:
    '@package':    'TYPO3.SingleSignOn.Server'
    '@controller': 'AccessToken'
    '@action':     'redeem'
    '@format':     'html'
  appendExceedingArguments: TRUE
