-
  name: 'SSO authentication with action'
  uriPattern: 'authentication/{@action}'
  defaults:
    '@package':    'TYPO3.SingleSignOn.Server'
    '@controller': 'Authentication'

-
  name: 'SSO authentication'
  uriPattern: 'authentication'
  defaults:
    '@package':    'TYPO3.SingleSignOn.Server'
    '@controller': 'Authentication'
    '@action':     'authenticate'

-
  name: 'Login with optional action'
  uriPattern: 'login(/{@action})'
  defaults:
    '@package':    'TYPO3.SingleSignOn.Server'
    '@controller': 'Login'
    '@action':     'index'
