-
  name: 'SSO authentication endpoint'
  uriPattern: 'authentication'
  defaults:
    '@package':    'TYPO3.SingleSignOn.Server'
    '@controller': 'Endpoint'
    '@action':     'authenticate'
    '@format':     'html'
  appendExceedingArguments: TRUE

-
  name: 'SSO access token redemption'
  uriPattern: 'token/{accessToken}/redeem'
  defaults:
    '@package':    'TYPO3.SingleSignOn.Server'
    '@controller': 'AccessToken'
    '@action':     'redeem'
    '@format':     'html'
  appendExceedingArguments: TRUE
